### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by name-liang** [Windsrain/Selective-Stereo#17]
When I run
`python evaluate_stereo.py --restore_ckpt ./pretrained_models/sceneflow.pth`

I get o error, it's details is:
`2024-10-10 14:23:23,659 INFO     [evaluate_stereo.py:229] Loading checkpoint...
evaluate_stereo.py:230: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(args.restore_ckpt)
2024-10-10 14:23:23,885 INFO     [evaluate_stereo.py:232] Done loading checkpoint
The model has 13.14M learnable parameters.
Traceback (most recent call last):
  File "evaluate_stereo.py", line 250, in <module>
    validate_sceneflow(model, iters=args.valid_iters, mixed_prec=use_mixed_precision)
  File "D:\anaconda3\envs\Selective_Stereo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "evaluate_stereo.py", line 123, in validate_sceneflow
    val_dataset = datasets.SceneFlowDatasets(dstype='frames_finalpass', things_test=True)
  File "D:\paper\Selective-Stereo\Selective-Stereo\Selective-IGEV\core\stereo_datasets.py", line 126, in __init__
    assert os.path.exists(root)
AssertionError`

i don`t kwon what happened, i hope for your help.
Thank you!!!

**Comment by Windsrain** [comment]
You need to change the root path to the path where your SceneFlow is located.




奇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Windsrain/Selective-Stereo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月10日(星期四) 下午2:29
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Windsrain/Selective-Stereo] AssertionError (Issue #17)





 
When I run
 python evaluate_stereo.py --restore_ckpt ./pretrained_models/sceneflow.pth
 
I get o error, it's details is:
 2024-10-10 14:23:23,659 INFO     [evaluate_stereo.py:229] Loading checkpoint... evaluate_stereo.py:230: FutureWarning: You are using torch.loadwithweights_only=False(the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value forweights_onlywill be flipped toTrue. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via torch.serialization.add_safe_globals. We recommend you start setting weights_only=True for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature. checkpoint = torch.load(args.restore_ckpt) 2024-10-10 14:23:23,885 INFO     [evaluate_stereo.py:232] Done loading checkpoint The model has 13.14M learnable parameters. Traceback (most recent call last): File "evaluate_stereo.py", line 250, in <module&gt; validate_sceneflow(model, iters=args.valid_iters, mixed_prec=use_mixed_precision) File "D:\anaconda3\envs\Selective_Stereo\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "evaluate_stereo.py", line 123, in validate_sceneflow val_dataset = datasets.SceneFlowDatasets(dstype='frames_finalpass', things_test=True) File "D:\paper\Selective-Stereo\Selective-Stereo\Selective-IGEV\core\stereo_datasets.py", line 126, in __init__ assert os.path.exists(root) AssertionError
 
i don`t kwon what happened, i hope for your help.
 Thank you!!!

**Comment by name-liang** [comment]
in fact,this is right path,I update two folder from Google Drive,and then, i place it like picture
![image](https://github.com/user-attachments/assets/5e476080-29cb-4b42-b650-5e8d8dc373dd)

**Comment by Windsrain** [comment]
core/stereo_datasets.py Line 124. Have you changed this root?
&nbsp;


奇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月10日(星期四) 下午2:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Windsrain/Selective-Stereo] AssertionError (Issue #17)














 
in fact,this is right path,I update two folder from Google Drive,and then, i place it like picture
 image.png (view on web)

**Comment by name-liang** [comment]
so i should change it to "sceneflow" folder in my cmoputer, and this folder have "sceneflow.pth"?

**Comment by Windsrain** [comment]
this root means the root of SceneFlow dataset, not ckpt.
&nbsp;


奇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月10日(星期四) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Windsrain/Selective-Stereo] AssertionError (Issue #17)














 
so i should change it to "sceneflow" folder in my cmoputer, and this folder have "sceneflow.pth"?

**Comment by name-liang** [comment]
oh,thanks,i think i understand.
Thank you!!!
